FROM ubuntu:22.04
RUN apt update && \
    apt -y install \
        autoconf \
        automake \
        build-essential \
        cargo \
        cbindgen \
        git \
        jq \
        libcap-ng-dev \
        libcap-ng0 \
        libevent-dev \
        libevent-pthreads-2.1-7 \
        libhiredis-dev \
        libjansson-dev \
        libjansson-dev \
        libmagic-dev \
        libnet1-dev \
        libnetfilter-queue-dev \
        libnetfilter-queue1 \
        libnfnetlink-dev \
        libnfnetlink0 \
        libpcap-dev \
        libpcre2-dev \
        libpython2.7 \
        libtool \
        libyaml-0-2 \
        libyaml-dev \
        make \
        parallel \
        python3-yaml \
        rustc \
        software-properties-common \
        sudo \
        zlib1g \
        zlib1g-dev
